# Generated by Django 3.0.5 on 2020-05-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='cotent',
        ),
    ]
