# Generated by Django 3.0.5 on 2020-05-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200523_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='article',
            new_name='articles',
        ),
    ]
