# Generated by Django 3.0.5 on 2020-05-24 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200524_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='articles.Articles'),
        ),
    ]
