# Generated by Django 3.0.5 on 2020-05-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_comments_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='articles.Articles'),
        ),
    ]
