# Generated by Django 3.0.5 on 2020-05-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200524_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='cotent',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='articles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='articles.Articles'),
            preserve_default=False,
        ),
    ]
